Repository showbie/backpack-tokens, pull requests merged in 2020-01, with the labels that each got.

#109 Breaking: Update all Grey colour values
  docs/colours/socrative/README.md
  src/backpack-socrative.js
Labels: breaking

#111 New: Add grey-200 to Showbie palette
  docs/colours/graveyard/README.md
  docs/colours/showbie/README.md
  src/backpack-showbie.js
Labels: added

#113 New: Add dark Slate colour
  docs/.vuepress/components/ColorScale.vue
  docs/.vuepress/components/ColorSwatch.vue
  docs/colours/graveyard/README.md
  docs/colours/showbie/README.md
  lib/build-colors.js
  src/backpack-showbie.js
  src/templates/showbie-color.js.hbs
Labels: added

#116 New: Add grey-100 to Showbie palette
  docs/colours/graveyard/README.md
  docs/colours/showbie/README.md
  src/backpack-showbie.js
Labels: added

#117 Build: Loosen Node engine requirement
  package.json
Labels: changed

#118 New: Add Showbie reds to Socrative palette
  docs/colours/socrative/README.md
  src/backpack-socrative.js
Labels: added

#119 New: Add indigo colours to Socrative palette
  docs/colours/socrative/README.md
  src/backpack-socrative.js
Labels: added

#86 Breaking: Rename Socrative orange to amber
  src/backpack-socrative.js
Labels: breaking, changed

#120 New: Add orange colours to Socrative palette
  docs/colours/socrative/README.md
  src/backpack-socrative.js
Labels: added

#121 Docs: Change ColorScale layout to a tighter grid
  docs/.vuepress/components/ColorScale.vue
  docs/colours/showbie/README.md
  src/backpack-showbie.js
Labels: changed

#122 New: Add 200-level Red colour
  docs/.vuepress/components/ColorScale.vue
  docs/colours/showbie/README.md
  docs/colours/socrative/README.md
  src/backpack-showbie.js
Labels: added
